import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import DashboardLayout from "@/layout/Layout";
import StyledComponentsRegistry from "@/lib/registry";

export const metadata: Metadata = {
  title: "Vrindavan Farm",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
       
      </head>
      <body>
        <StyledComponentsRegistry>
        <DashboardLayout>{children}</DashboardLayout>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
